name: 'CI'
on:
  pull_request:

jobs:
  lint-build-check-test-and-use:
    name: Lint, Build, Check, Test and Use
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          node-version-file: '.node-version'

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Lint
        run: |
          pnpm run lint

      - name: Build
        run: |
          pnpm run build

      - name: Check repo status
        run: |
          repo_status=$(git status --porcelain)
          if [[ ! -z "${repo_status}" ]]; then
            echo "::error::Uncommitted changes detected"
            echo "${repo_status}"
            git status -vv
            exit 1
          fi

      - name: Test
        run: |
          pnpm run test

      - name: Generate a policy from template to test the action
        run: |
          mkdir -p policies && templates/replace.sh templates/policy.template.yaml > policies/policy.yaml

      - name: Add generated policy file and amend the latest commit temporarily
        run: |
          git add -f policies/policy.yaml && git -c "user.name=cerbos-store-action-ci" -c "user.email=sdk@cerbos.dev" commit --amend --no-edit

      - name: Use action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          api_endpoint: '${{ secrets.CERBOS_HUB_API_ENDPOINT }}'
          client_id: '${{ secrets.CERBOS_HUB_CLIENT_ID }}'
          client_secret: '${{ secrets.CERBOS_HUB_CLIENT_SECRET }}'
          store_id: '${{ secrets.CERBOS_HUB_STORE_ID }}'
          subdir: 'policies'
          to_revision: HEAD
          from_revision: HEAD^
