name: 'CI'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-build-test-and-use:
    name: Lint, Build, Test, Check and Use
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          node-version-file: '.node-version'

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Lint
        run: |
          pnpm run lint
